sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2005o921LLn%.
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: com-lin-01